"""Server-generated record codes (#197).

`customer.code` was required, so a clerk with no code to enter typed a placeholder. The data shows
it: of 10,933 rows, 1,634 are duplicates, 12 are `IT-<epoch-ms>` values generated by hand, and the
rest split between bare integers and `ID<digits>` — two conventions and a lot of noise.

The generated value has to stay out of both conventions, because both are shapes a human still
types, and it has to be recognisable afterwards so support can tell "never had a code" from "the
code is six digits".
"""

import re

from app.utils.codes import CUSTOMER_PREFIX, generate_code

#: Enough to make a one-in-a-million property show up, cheap enough to run every time.
SAMPLE = 2000


def test_it_is_the_prefix_plus_a_token() -> None:
    assert re.fullmatch(r'CUS-[0-9A-Z]{8}', generate_code(CUSTOMER_PREFIX))


def test_it_fits_the_column() -> None:
    """`varchar(25)`, and mbe_dev already has codes using all 25."""
    assert len(generate_code(CUSTOMER_PREFIX)) <= 25


def test_it_matches_neither_live_convention() -> None:
    """1,292 rows are bare integers and 1,281 are `ID<digits>`; a generated code that looked like
    either would eventually land on a value someone meant to type."""
    for _ in range(SAMPLE):
        code = generate_code(CUSTOMER_PREFIX)
        assert not re.fullmatch(r'[0-9]+', code)
        assert not re.fullmatch(r'ID[0-9]+', code)


def test_it_avoids_the_characters_a_human_mistypes() -> None:
    """0/O, 1/I/L are the transcription pairs; U is excluded so a token cannot spell a word."""
    forbidden = set('01ILOU')
    seen = {
        c for _ in range(SAMPLE) for c in generate_code(CUSTOMER_PREFIX)[len(CUSTOMER_PREFIX) :]
    }
    assert not seen & forbidden
    assert len(seen) == 30, 'every character in the alphabet should be reachable'


def test_it_does_not_repeat() -> None:
    """Unique by construction, which is what lets this ship without an index or a retry: the
    column carries no index at all, so a check-then-insert could not close the race anyway."""
    assert len({generate_code(CUSTOMER_PREFIX) for _ in range(SAMPLE)}) == SAMPLE


def test_the_prefix_is_a_parameter_not_a_constant() -> None:
    """#197 asked that customers and products not end up with two different-looking machine
    codes. A second caller changes the prefix and keeps the scheme."""
    assert generate_code('PRD-').startswith('PRD-')
    assert len(generate_code('PRD-', length=4)) == len('PRD-') + 4
